import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Button } from "@/components/ui/button";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative antialiased bg-neutral-900`}
      >
        <nav className="w-full flex items-center justify-between py-10 max-w-7xl mx-auto z-10">
          <Image src="/logo-white.svg" alt="logo" width={180} height={100} />
          <Button className="cursor-pointer bg-neutral-800">Connect Wallet</Button>
        </nav>
        {children}
      </body>
    </html>
  );
}
